# Demo purpose!! 
# This must come from external secret.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {
        "database": {
          "user": "postgres",
          "host": "{{ .Release.Name }}-postgresql",
          "database": "db",
          "password": "pass",
          "port": 5432
        }
    }