apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  app.config.json: |
    {
      "baseUrl": "https://nodejs-backend-{{ .Release.Namespace }}.{{ .Values.baseDomain}}/api"
    }

