# Demo purpose!! 
# This must come from external secret.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |
    {
        "host": "postgres",
        "port": "5432",
        "username": "user",
        "password": "pass",
        "database": "db"
    }