# Demo purpose!! 
# This must come from external secret.
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "java-app.fullname" . }}
  labels:
    {{- include "java-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secretData | toYaml }}
    