---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/managed-by: quarkus
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.app.ports.http }}
  selector:
    app.kubernetes.io/name: openshift-quickstart
  type: ClusterIP
